apiVersion: v1
kind: PersistentVolume
metadata:
  name: scvol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scvol
  hostPath:
    path: /tmp/kube